a = input("Digite algo: ")
print("O tipo primitivo desse valor é ", type(a))
print("só tem espaços? ", a.isspace())
print('é um numero? ', a.isnumeric())
print('é alphanumérico?', a.isalnum())
print('está em maiusculas?', a.isupper())
print('esta em minusculas? ', a.islower())
print('esta capitalizada?', a.istitle())
